### ISSUE TITLE
Alignment issue in flex box in team intro page

### ISSUE THREAD

**Issue by Anu9969** [vinitvijal/acm-sscbs-next#2]
![image](https://github.com/user-attachments/assets/b3add1a3-5fe8-4bc7-90ac-58e4124fd134)

**Comment by vinitvijal** [comment]
@Anu9969 Show me what you got

**Comment by Anu9969** [comment]
![image](https://github.com/user-attachments/assets/e3fa479e-eda2-406f-9d6c-b9c49a93e535)
